package com.infosys.carbonfootprint.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Keeps created_at present on the application's record tables and backfills
 * legacy rows that predate the created_at feature. New row timestamps are
 * generated by Hibernate via @CreationTimestamp on the entities.
 */
@Component
@Order(1)
public class CreatedAtDatabaseInitializer implements CommandLineRunner {

    private static final String[] TABLES = {
            "users",
            "addresses",
            "government_ids",
            "roles",
            "categories",
            "activity_types",
            "emission_factors",
            "activity_logs",
            "goals",
            "articles",
            "alerts",
            "emission_limits"
    };

    private final DataSource dataSource;

    public CreatedAtDatabaseInitializer(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public void run(String... args) throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {

            // Keep legacy emission-limit rows compatible with the current entity model.
            statement.executeUpdate("ALTER TABLE IF EXISTS emission_limits ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ACTIVE'");
            statement.executeUpdate("UPDATE emission_limits SET status = 'ACTIVE' WHERE status IS NULL");
            statement.executeUpdate("ALTER TABLE IF EXISTS emission_limits ALTER COLUMN status SET DEFAULT 'ACTIVE'");

            for (String table : TABLES) {
                statement.executeUpdate(
                        "ALTER TABLE IF EXISTS " + table +
                        " ADD COLUMN IF NOT EXISTS created_at TIMESTAMP"
                );

                // Existing records did not historically have this value.
                // Backfill them with the current server/database timestamp so
                // every existing row has a usable persisted date/time.
                statement.executeUpdate(
                        "UPDATE " + table +
                        " SET created_at = CURRENT_TIMESTAMP" +
                        " WHERE created_at IS NULL"
                );
            }
        } catch (SQLException ex) {
            throw new IllegalStateException("Unable to prepare created_at columns", ex);
        }
    }
}
