package com.infosys.carbonfootprint.dto;

import com.infosys.carbonfootprint.entity.CategoryStatus;
import jakarta.validation.constraints.*;
import lombok.*;

import java.time.LocalDateTime;

@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class ActivityTypeDto {
    private Long activityTypeId;

    @NotNull(message = "Category is required")
    private Long categoryId;

    private String categoryCode;
    private String categoryName;

    // Optional: a deterministic code is generated by the service when blank.
    @Pattern(regexp = "^$|^[A-Z0-9_]{2,20}$", message = "Activity code must be 2-20 uppercase letters, digits or underscores")
    private String activityCode;

    @NotBlank(message = "Activity name is required")
    @Size(min = 2, max = 100)
    private String activityName;

    @Size(max = 500)
    private String description;

    @NotBlank(message = "Unit is required")
    @Size(max = 20)
    private String unit;

    private Double minQuantity;
    private Double maxQuantity;
    private Double defaultQuantity;
    private Integer displayOrder;
    private String icon;

    @NotNull(message = "Status is required")
    private CategoryStatus status;

    private String remarks;
    private String createdBy;
    private String updatedBy;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
